version: '3'
services:
  bot:
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      # Update these with the variables set in the .env file
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gonyx
    volumes:
    - ./.postgres:/var/lib/postgresql/data